### ISSUE TITLE
Bug in router

### ISSUE THREAD

**Issue by gbishop** [mweststrate/state-routing-blog-sources#2]
First, thanks for this code.

I think there is a bug in https://github.com/mweststrate/state-routing-blog-sources/blob/master/src/store/router.js#L18 where the === seems unlikely to ever return true because currentPath is computed object and window.location.pathname is a string. I was getting extra calls to pushState until I used toJSON to force the currentPath to a string.

**Comment by mweststrate** [comment]
Mind to create a PR to address this?

**Comment by gbishop** [comment]
Now, I'm not so sure. In your code the value of currentPath is a string so the === comparison works properly. In my code that value is a ComputedValue object. 

My version of currentPath is:
```
currentPath = computed(() => process.env.PUBLIC_URL + `/${this.count}`);
```
And yours is:
```
    @computed get currentPath() {
        switch(this.currentView.name) {
            case "overview": return "/document/"
            case "document": return `/document/${this.currentView.documentId}`
        }
    }
```
I didn't expect your version to produce a different result. I don't think the difference is in the decorator. What is it?

**Update**: moving my currentPath function into the extendObservable makes it behave like yours so I don't have to use toJSON().

Clearly, I've still got a lot to learn. 

Sorry for the distraction.

**Comment by gbishop** [comment]
Clearly the bug was my misunderstanding, not you code. Closing the issue.
